#!/bin/bash

set -ex

DOCKER_OPTS=${DOCKER_OPTS:-}
if [ ! -z "$PORT" ]; then
  DOCKER_OPTS="$DOCKER_OPTS -p $PORT:$PORT"
fi

docker run \
  -i \
  -t \
  -v $PWD:/workdir \
  -e PORT=$PORT \
  -e APP_HOST=$APP_HOST \
  $DOCKER_OPTS \
  ljfranklin/middleman \
  "$@"
