#!/bin/bash
set -eux

APP_NAME=${1:-homepage}
MANIFEST_FILE=${2:-manifest.yml}
EXTERNAL_URL="lylefranklin.com"

SCRIPTS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PROJECT_DIR=$(cd $SCRIPTS_DIR/.. && pwd)

pushd $PROJECT_DIR
  cf zero-downtime-push $APP_NAME -f $MANIFEST_FILE
  cf map-route $APP_NAME $EXTERNAL_URL
  cf map-route $APP_NAME www.$EXTERNAL_URL
popd
